/*
First task is UI Navigation Highlighter.
I will need to make the div that is clicked change background color, text to bold, and reverts the other divs to be the original syle.
Either will need to make multiple functions that depending on what div is click will result in what function is called upon.
OR I could possibly make a single funciton and the code detects what div is being clicked applies the different stlye to that div 
while the other divs get changed to the original stlye.


The next task is Rock Paper Scissors (Guard)
Will need to make a score board starting at 0 points.
Will need to make the computer pick a number between 0-3 and round up.
Make 1 = rock, 2 = paper, 3 = scissors.
Then need to make four buttons on html for the user to select what they want to play.
Give those choices a value 0 = Guard, 1 = rock, 2 = paper, 3 = scissors.
Will then need a javascript that will check the results for a winner, tie, or loser, if the player chooses guard, then skip the checking the results.
The javascript will then need to determine what happens to the scores based on these results.
Guard = -.5, win = +1, tie = +0, loss = -1
Then have the text "You chose PLAYERCHOICE, computer chose COMPUTERCHOICE"
Followed by the new score.
*/